const { colors, pick, ui } = require("../config")

module.exports = {
   // "diffEditor.insertedTextBackground":"#f00", 
   // "diffEditor.insertedTextBorder":"#f00", 
   // "diffEditor.removedTextBackground":"#f00", 
   // "diffEditor.removedTextBorder":"#f00", 
   // "diffEditor.border":"#f00", 
   // "diffEditor.diagonalFill":"#f00", 
   // "diffEditor.insertedLineBackground":"#f00", 
   // "diffEditor.removedLineBackground":"#f00", 
   // "diffEditorGutter.insertedLineBackground":ui.barBackground.rgb, 
   // "diffEditorGutter.removedLineBackground":ui.barBackground.rgb, 
   // "diffEditorOverview.insertedForeground":"#f00", 
   // "diffEditorOverview.removedForeground":"#f00", 
   // "diffEditor.unchangedRegionBackground":"#f00", 
   // "diffEditor.unchangedRegionForeground":"#f00", 
   // "diffEditor.unchangedRegionShadow":"#f00", 
   // "diffEditor.unchangedCodeBackground":"#f00", 
   // "diffEditor.move.border":"#f00", 
   // "diffEditor.moveActive.border":"#f00", 
   // "multiDiffEditor.headerBackground":"#f00", 
   // "multiDiffEditor.background":"#f00", 
   // "multiDiffEditor.border":"#f00", 
}
